# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c2e8ee74f23f09255fa267f2bd41acf8aa57e0278534f1c0e81b4b2dc4e916039c33d5f6060e180af2c5f035bc46845f4908be64e6cb395808577571e5f709f

test:
  secret_key_base: cd5385a6094e1a8daf90adc309142561e330ee1f26d321add9ebcfd5d2a67a133c0c56152f557364a0c2663cdb52f3921ad62e58c77eaf7c806a9727101e2b4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
